# Generated by Django 5.0 on 2025-11-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='servidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horario_app.servidor'),
            preserve_default=False,
        ),
    ]
