# Generated by Django 5.2.8 on 2025-11-12 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practicante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_discord', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('semestre', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_recuperacion', 'En Recuperación'), ('en_riesgo', 'En Riesgo')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PracticanteReforzamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('area', models.CharField(default='Falta agregar', max_length=100)),
                ('motivo', models.TextField(default='Falta agregar')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en_reforzamiento', 'En Reforzamiento'), ('completado', 'Completado'), ('reintegrado', 'Reintegrado')], default='en_reforzamiento', max_length=20)),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reforzamientos', to='practicantes.practicante')),
            ],
            options={
                'verbose_name': 'Practicante en Reforzamiento',
                'verbose_name_plural': 'Practicantes en Reforzamiento',
                'db_table': 'practicantes_reforzamiento',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
