# Generated by Django 5.2.6 on 2025-11-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicantes', '0002_asistencia_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retraso', 'Retraso'), ('falta', 'Falta'), ('inasistencia', 'Inasistencia'), ('otro', 'Otro')], max_length=20)),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], default='leve', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertencias', to='practicantes.practicante')),
            ],
            options={
                'verbose_name': 'Advertencia',
                'verbose_name_plural': 'Advertencias',
                'db_table': 'advertencia',
                'ordering': ['-fecha'],
            },
        ),
    ]
