# Generated by Django 5.2.8 on 2025-12-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicantes', '0003_advertencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionPracticante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('registro', 'Registro'), ('actualizacion', 'Actualización'), ('eliminacion', 'Eliminación'), ('advertencia', 'Advertencia'), ('sancion', 'Sanción'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('activo', 'Activo'), ('en_recuperacion', 'En Recuperación'), ('en_riesgo', 'En Riesgo')], max_length=50)),
                ('numero_advertencia', models.PositiveIntegerField(blank=True, null=True)),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='practicantes.practicante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción de Practicante',
                'verbose_name_plural': 'Acciones de Practicantes',
                'db_table': 'accion_practicante',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
