# Generated by Django 5.0 on 2025-11-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Practicante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicantes', to='horario_app.servidor')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario_app.practicante')),
            ],
            options={
                'unique_together': {('practicante', 'dia')},
            },
        ),
    ]
