# Generated by Django 5.0 on 2025-11-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario_app', '0002_horario_servidor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='practicante',
            name='servidor',
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(max_length=20),
        ),
    ]
